CREAT TABLE VAGA(
	ID_VAGA INT NOT NULL,
	SECAO_VAGA VARCHAR(2) NOT NULL,
	ANDAR_VAGA INT NOT NULL,
	ESTADO_VAGA VARCHAR(2) NOT NULL,
	CIDADE_VAGA VARCHAR(20) NOT NULL,
	CEP_VAGA VARCHAR(9) NOT NULL,
	HORARIO_RESERVA TIME NOT NULL,
	PRECO_VAGA FLOAT NOT NULL
	PRIMARY KEY(CEP_VAGA)
	);

CREAT TABLE EMPRESA(
	EMPRESA_RESP VARCHAR(30) NOT NULL,
	CNPJ_EMPRESA VARCHAR(18) NOT NULL,
	PRIMARY KEY(CNPJ_EMPRESA)
	);
	
CREAT TABLE ADMINISTRADOR(
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	ID_ADMINISTRADOR SERIAL NOT NULL,
	PRIMARY KEY(ID_ADMINISTRADOR)
	);

CREAT TABLE CONDUTOR(
	NOME VARCHAR(30) NOT NULL,
	CPF_CONDUTOR VARCHAR(14) NOT NULL,
	EMAIL_CONDUTOR VARCHAR(30) NOT NULL,
	TEL_CONDUTOR VARCHAR(15) NOT NULL,
	PRIMARY KEY(CPF_CONDUTOR)
	);
	

CREAT TABLE SENSOR(
	IDSENSOR SERIAL NOT NULL,
	SITUAÇAO VARCHAR(3) NOT NULL,
	TIPO VARCHAR(11) NOT NULL,
	ID_VAGA INT NOT NULL,
	PRIMARY KEY(ID_VAGA),
	FOREIGN KEY(SENSOR),
	REFERENCES(VAGA)
	);

CREAT TABLE VEICULO(
	PLACA_VEICULO VARCHAR(8) NOT NULL,
	CATEG_VEICULO VARCHAR(1) NOT NULL,
	PRIMARY KEY(CATEG_VEICULO)
	);
	
CREAT TABLE PAGAMENTO(
	METODO INT NOT NULL,
	VALOR FLOAT NOT NULL,
	PRIMARY KEY(METODO)
	);

CREAT TABLE RESERVA(
	DATA_RESERVA DATE NOT NULL,
	HORA_ENTRADA TIME NOT NULL,
	HORA_SAIDA TIME NOT NULL,
	PRIMARY KEY (DATA_RESERVA)
	);